/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/daschulz/igvcCode/CPRC-IGVC/Code/Software Implementation/RosIntegration/rosWksp/src/beagle_pkg/srv/dem.srv
 *
 */


#ifndef BEAGLE_PKG_MESSAGE_DEM_H
#define BEAGLE_PKG_MESSAGE_DEM_H

#include <ros/service_traits.h>


#include <beagle_pkg/demRequest.h>
#include <beagle_pkg/demResponse.h>


namespace beagle_pkg
{

struct dem
{

typedef demRequest Request;
typedef demResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct dem
} // namespace beagle_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beagle_pkg::dem > {
  static const char* value()
  {
    return "7e99c275c708f2a944f8a662652face0";
  }

  static const char* value(const ::beagle_pkg::dem&) { return value(); }
};

template<>
struct DataType< ::beagle_pkg::dem > {
  static const char* value()
  {
    return "beagle_pkg/dem";
  }

  static const char* value(const ::beagle_pkg::dem&) { return value(); }
};


// service_traits::MD5Sum< ::beagle_pkg::demRequest> should match 
// service_traits::MD5Sum< ::beagle_pkg::dem > 
template<>
struct MD5Sum< ::beagle_pkg::demRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beagle_pkg::dem >::value();
  }
  static const char* value(const ::beagle_pkg::demRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beagle_pkg::demRequest> should match 
// service_traits::DataType< ::beagle_pkg::dem > 
template<>
struct DataType< ::beagle_pkg::demRequest>
{
  static const char* value()
  {
    return DataType< ::beagle_pkg::dem >::value();
  }
  static const char* value(const ::beagle_pkg::demRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beagle_pkg::demResponse> should match 
// service_traits::MD5Sum< ::beagle_pkg::dem > 
template<>
struct MD5Sum< ::beagle_pkg::demResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beagle_pkg::dem >::value();
  }
  static const char* value(const ::beagle_pkg::demResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beagle_pkg::demResponse> should match 
// service_traits::DataType< ::beagle_pkg::dem > 
template<>
struct DataType< ::beagle_pkg::demResponse>
{
  static const char* value()
  {
    return DataType< ::beagle_pkg::dem >::value();
  }
  static const char* value(const ::beagle_pkg::demResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEAGLE_PKG_MESSAGE_DEM_H
